### ISSUE TITLE
MACOSX_DEPLOYMENT_TARGET and MACOSX_SDK_VERSION: 

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/powerloader-feedstock#3]
### Comment:

It's weird that the `conda_build_config.yaml` that was in the staged-recipes did not get carried over in the `recipe` directory here.

It looks like a bug of the recipe generation.

**Comment by SylvainCorlay** [comment]
cc @johanmabille

it may be required to re-add it so that the next rerender does not get back to an earlier version of the SDK.

**Comment by JohanMabille** [comment]
It get carried over and I removed it since the errors on OS 10.15 can be removed with the `D_LIBCPP_DISABLE_AVAILABILITY` flag. See https://github.com/conda-forge/powerloader-feedstock/pull/2/files.
